### ISSUE TITLE
Code factor is not in sync with ESLint

### ISSUE THREAD

**Issue by vamshi9** [codefactor-io/codefactor#19]
Recently, I have updated the dev dependencies of eslint to their latest stable versions. When I run lint --fix command locally, I see 0 issues. But when ran through code factor, I see the issues. I am not sure how code factor is evaluating the rules set in .eslintrc.json.

**Local:**
![image](https://user-images.githubusercontent.com/11611776/86528842-7fcbfb80-bec9-11ea-8777-b00efd7ff443.png)

**Code factor:**
![image](https://user-images.githubusercontent.com/11611776/86528850-9b370680-bec9-11ea-9c8a-53af84bce15e.png)

**.eslintrc.json**
![image](https://user-images.githubusercontent.com/11611776/86529076-498f7b80-becb-11ea-82c4-288707f27b6c.png)

**package..json**
![image](https://user-images.githubusercontent.com/11611776/86529086-6035d280-becb-11ea-9f48-ad32b2645a6d.png)

I had to add all the eslint rules because code factor was throwing the error. But now, I want to know the core reason for it. I think I can't keep proceeding in adding the rules where my local and code factor are not in sync.

Any idea?

**Comment by cordis-dev** [comment]
@vamshi9 thanks for reporting. We've updated how ESLint errors are reported, so if you go to your repo `Settings` page, you should see a more detailed explanation of what went wrong.

For your case it's related to invalid rule configuration value which is usually caused by mismatched ESLint versions. To see what version and plugins we use please visit https://support.codefactor.io/i24-analysis-tools-open-source.
