### ISSUE TITLE
Detect more shell shebangs

### ISSUE THREAD

**Issue by MichaIng** [codefactor-io/codefactor#29]
This spring, support for shell scripts without file ending, detected via shebang, has been added, which is awesome: https://github.com/codefactor-io/codefactor/issues/2#issuecomment-623287639

We started to use `#!/bin/dash` as shebang in cases where we want to assure that a lightweight bourne shell is used instead of the in comparison relatively heavy-weight bash, as `sh` is usually a symlink that can be easily adjusted via alternatives systems to point to any other shell.

Hence my request to detect a few more known shell implementations:
```
#!/bin/dash
#!/usr/bin/env dash
#!/bin/ash
#!/usr/bin/env ash
#!/bin/csh
#!/usr/bin/env csh
#!/bin/ksh
#!/usr/bin/env ksh
#!/bin/zsh
#!/usr/bin/env zsh
```
There would be a few derivations of course. I don't know how it is implemented currently, but an extended regex would do, like:
```
[[ $(head -1 file) =~ ^'#!/'(bin/|usr/bin/env )(|ba|da|a|c|k|z)'sh' ]] && <check it>
```

**Comment by cordis-dev** [comment]
@MichaIng thanks for reporting. We've now extended shell dialect list to support `sh`, `ash`, `bash`, `dash`, `bats` and `ksh`. This is based on https://github.com/koalaman/shellcheck/blob/master/src/ShellCheck/Parser.hs#L3268 since ShellCheck is our primary tool here. 

See https://github.com/koalaman/shellcheck/wiki/SC1071 for more details.

**Comment by MichaIng** [comment]
That is great, many thanks for the quick and satisfying implementation! A I didn't know about the csh and zsh limitation of shellcheck, makes sense to simply follow the official support list then 👍.
