### ISSUE TITLE
Duplicate Code issue in DbContext class

### ISSUE THREAD

**Issue by martinussuherman** [codefactor-io/codefactor#37]
Dear codefactor,

I'm not sure, but maybe for DbContext class, the Duplicate Code rule should have been relaxed a bit?
This is the generated issue: https://github.com/martinussuherman/PsefApiOData/issues/5
Thank you for your attention.

Regards,

Martinus

**Comment by cordis-dev** [comment]
@martinussuherman thanks for reporting. Currently we do not see a viable solution for this, since this is context-specific i.e. hard to determine good defaults, has possible performance issues and opens precedent for other similar requests. We usually ignore source code comments and comment blocks which are based on language.

Ability to _control_ duplication thresholds could address this issue, but it would be added for repo branch only.

You can still disable such issues via ignore action.  Please check https://support.codefactor.io/i18-ignoring-issues-and-patterns for more.
