### ISSUE TITLE
Function marked as unused in JS file although it is used in EJS

### ISSUE THREAD

**Issue by dladeira** [codefactor-io/codefactor#39]
I have a function in a JS file named "acceptCookie()", and it is used in a EJS file like this
`<button onclick="acceptCookie()">Accept Cookies</button>`
but codefactor marks it as defined but never used.

**Comment by cordis-dev** [comment]
@dladeira thanks for reporting. Could your provide CodeFactor link to the file in question? If repo in question is private please write directly at https://www.codefactor.io/contact.

**Comment by dladeira** [comment]
I cannot do that as I already fixed the issue by using DOM to register the events instead of HTML, but I know the issue still exists.

Steps to replicate it

Using nodeJS serve the user a simple EJS file with the following button
`<button onclick="acceptCookie()">Accept Cookies</button>`
Write a simple JS file and link it to the EJS file
`function acceptCookie() {
alert("cookie has been accepted!")`
link:
`<script src="PATH/TO/SCRIPT"></script>`

codeFactor.io will mark the acceptCookie() function as defined but never used.

**Comment by cordis-dev** [comment]
ESLint linter is being used to emit this warning and this appears to be a limitation of `no-unused-vars` rule since the usage in this case is outside of JS file. See https://eslint.org/docs/rules/no-unused-vars#exported for possible resolution.

You can also ignore issues as you see fit on CodeFactor - see https://support.codefactor.io/i18-ignoring-issues-and-patterns
